# system settings for each session
SOFT_CODE_PRESENT_STIMULUS = 1
SOFT_CODE_START_OPEN_LOOP = 2
SOFT_CODE_STOP_OPEN_LOOP = 3
SOFT_CODE_END_PRESENT_STIMULUS = 4
SOFT_CODE_START_LOGGING = 5
SOFT_CODE_END_LOGGING = 6
SOFT_CODE_STOP_CLOSE_LOOP = 7
SOFT_CODE_WHEEL_NOT_STOPPING = 8
# rotary encoder
WHEEL_DIAMETER = 6.3
BIT_MESSAGE_RESET_ROTARY_ENCODER = 1
ROTARY_ENCODER_THRESHHOLD_LEFT = "RotaryEncoder1_4"
ROTARY_ENCODER_THRESHHOLD_RIGHT = "RotaryEncoder1_3"
STIMULUS_LEFT = "RotaryEncoder1_2"
STIMULUS_RIGHT = "RotaryEncoder1_1"
# stimulus
FPS = 60
SCREEN_WIDTH = 6144
SCREEN_HEIGHT = 1536
MONITOR_DISTANCE = 16  # Distance between subject's eyes and monitor
MONITOR_WIDTH = 60  # Width of your monitor in cm
