name: CodeCov

on:
  pull_request:
    branches: [master, develop]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      os: ubuntu-latest
      python-version: "3.8"

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install nose2
          pip install coverage
      - name: Generate Report
        run: |
          python -m nose2 -v -B -s tests/integration --with-coverage
          python -m coverage xml
      - name: Upload Coverage to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
